CREATE ROLE dex PASSWORD 'dex' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE ROLE neo PASSWORD 'neo' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE DATABASE dex;
CREATE DATABASE neo;
 \connect dex;
CREATE SCHEMA dex;

